Use MMTk builder API
mmtk/mmtk-openjdk pull request #166
Opened 2022-07-19 02:02 UTC by qinsoon

2022-07-19 13:41 UTC, wks requested changes
If appropriate, we may remove the Cargo features that select plans, because we can now select plan from the command line.

There are some `#include` unused.  They may be added by mistake.

The use of `Relaxed` memory order in this PR is correct, but may need explanation.

2022-07-19 13:41 UTC, wks commented on mmtk/src/lib.rs
> +        MMTK_INITIALIZED.store(true, std::sync::atomic::Ordering::Relaxed);
~~This should be `Release` (or `SeqCst` if we want to be more conservative).~~

`Relaxed` should be is OK here.

2022-07-20 05:58 UTC, qinsoon commented on mmtk/src/api.rs
> +    memory_manager::process(&BUILDER, "plan", "Immix");
Yeah, we still need them. The current CI scripts use those features. But we should be able to remove them very soon after I rewrite the CI scripts.

2022-07-20 07:07 UTC, qinsoon commented on mmtk/src/api.rs
> +    memory_manager::process(&BUILDER, "heap_size", size.to_string().as_str())
I have changed this.

2022-07-20 07:08 UTC, qinsoon commented on openjdk/mmtkHeap.cpp
> +using namespace std;
Yeah. I was trying to convert the heap size to a string in C++, but the OpenJDK's checker warned me that `new` is not allowed. So I moved the code to Rust, and forgot to remove the imports.

2022-07-20 07:09 UTC, qinsoon commented on mmtk/src/api.rs
> +    crate::MMTK_INITIALIZED.load(std::sync::atomic::Ordering::Relaxed)
I changed the memory order to `SeqCst`.

2022-07-20 07:14 UTC, wks approved these changes
LGTM

2022-07-21 02:14 UTC, merged